### ISSUE TITLE
CI testing workflow dependency installation issue

### ISSUE THREAD

**Issue by speediedan** [Lightning-AI/tutorials#177]
## 🐛 Bug
CI testing currently failing to install ffmpeg with the following error(s)

`Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavutil56_4.2.4-1ubuntu0.1_amd64.deb  404  Not Found [IP: 40.119.46.219 80]`
...
PR is forthcoming that will add sudo apt-get update to the install dependencies job
### To Reproduce

Run the CI testing job
See error like the below:
https://github.com/PyTorchLightning/lightning-tutorials/runs/6839199437?check_suite_focus=true
### Expected behavior

Expect the CI testing dependencies to install successfully

**Comment by Borda** [comment]
@speediedan, do you still see this issue? I gues it was just temporarily outage... :otter:

**Comment by speediedan** [comment]
> @speediedan, do you still see this issue? I gues it was just temporarily outage... otter

Thanks for checking back in @Borda, I haven't tested recently but I'm pretty sure this was either ephemeral or more likely addressed by the image update so this should be able to be closed.
