### ISSUE TITLE
replace tensorboard by CSVLogger

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/tutorials#19]
## 🚀 Feature
Replace inline tensorboard (TB) with a simple chart from standard CSLoggers 

### Motivation

The inline tensorboard is a cool interactive tool, but:
- it requires saved logos that are missing in the notebook
- TB inside notebooks is a heavy JS object (~30MB)

### Pitch

A reader would also see the progress immediately, maybe add plotting to the csvlogger?

### Alternatives

Some other simple logger?

**Comment by InCogNiTo124** [comment]
I'd like to work on this :)

**Comment by Borda** [comment]
Cool, let's do all in one PR 🐰

**Comment by InCogNiTo124** [comment]
@Borda im not sure how do I add plotting to the csv logger?

**Comment by Borda** [comment]
> @Borda im not sure how do I add plotting to the csv logger?

see the visualization over here: https://github.com/Borda/kaggle_plant-pathology/blob/main/notebooks/Plant-Pathology-with-Lightning.ipynb

**Comment by InCogNiTo124** [comment]
Hey, I'm just letting you know that I won't be able to finish this up. Someone else should take it. sorry!
