### ISSUE TITLE
`validate docs / build-docs` is failing in master

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/tutorials#204]
## 🐛 Bug
One of the required jobs is currently failing and blocking all ongoing PRs, such as #202 and #203.
```
validate Docs / build-docs (pull_request) 
```
### To Reproduce
https://github.com/Lightning-AI/tutorials/actions/runs/3332023469/jobs/5512626237

### Expected behavior
No error

**Comment by akihironitta** [comment]
It turned out to be an issue still. The current workaround is to modify something of the kornia notebook src. See https://github.com/Lightning-AI/tutorials/pull/205.

**Comment by Borda** [comment]
yes, the root is that there was some issue with pushing secrets to the last build a half year ago... so closing this issue in favor of #205
