### ISSUE TITLE
Refactor Mnist Hello World Example

### ISSUE THREAD

**Issue by ishandutta0098** [Lightning-AI/tutorials#240]
### Motivation

I have refactored the entire mnist hello world example, maintaining a similar structure but much more readable. 

### Pitch

The following are the major changes:
- Addition of a dataclass config instead of hardcoded config values
- Change in the implementation style of the forward function of MNISTModel 
- Add the `ckpt_path` argument to `trainer.test()` to suppress the warning
- Addition of docstrings to all classes and methods
- Addition of type hints for all parameters
- Addition of comments as and when required

### Additional context

I am a member of the Lightning League and the refactoring has been discussed with @Borda

**Comment by Wink35** [comment]
Minist
