### ISSUE TITLE
consolidate GPU test and publish

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/tutorials#286]
## 🚀 Feature

Let's re-consider the advantage of running `pytest` (e.g. `pytest -v notebook.ipynb  --nbval`) since notebooks in most cases do not include any real pytest case (well, I do not see any)

### Pitch

simplify the CI/CD processes

### Alternatives

adding at least fail fast for `pytest-nbval`

### Additional context

as a disadvantage, it tries to execute all related cell not fail fast which:
- marked looking for the issue harder as there is too much noise
- in most cases when the first failing cell hits, no others are passing because of missing expected imports or variables

**Comment by speediedan** [comment]
Makes sense since the testing was adding minimal marginal value over the publish pipeline. Totally on board with that simplification!

**Comment by Borda** [comment]
done in #324
