### ISSUE TITLE
`git-lfs` binary not resolving in .git post-checkout hook preventing a number of notebook updates from being published

### ISSUE THREAD

**Issue by speediedan** [Lightning-AI/tutorials#290]
## 🐛 Bug
The `Lightning-AI.tutorials [publish]` Azure pipeline [has been failing](https://dev.azure.com/Lightning-AI/Tutorials/_build?definitionId=29&_a=summary) since October 12th.

The issue was first observed a few months ago but apparently is rearing its ugly head again. The publish pipeline typically fails with the "papermill" job on the "Git check & switch branch" step:
```bash
 publication
 Previous HEAD position was 3b4e9a0 docker: add missing `git-lfs` & readability (#284)
 Switched to branch 'publication'
 Your branch is behind 'origin/publication' by 10 commits, and can be fast-forwarded.
   (use "git pull" to update your local branch)

 This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.

 ##[error]Bash exited with code '1'.
 ```

The last `papermill` job component of the [publish pipeline to succeed](https://dev.azure.com/Lightning-AI/Tutorials/_build/results?buildId=178971&view=logs&j=dc90ad39-3c96-559d-d154-a89bc7e884c1&t=44358e4e-f53a-5d13-8521-c4b3b394d5d6&l=17) was the publishing of an updated version of `course_UvA-DL/13-contrastive-learning` triggered by `c0d526ed5b4b4f27f8f4b3f5b0c4bac5b39d0d4c` 

The transition sequence from the final successful job to the failing ones:
1. `c0d526ed5b4b4f27f8f4b3f5b0c4bac5b39d0d4c` gets checkout from main, changes wrt publication branch are detected and main is merged into publication and pushed successfully
2. `course_UvA-DL/13-contrastive-learning` gets updated, committed and pushed to origin/publication at `5497c9a8dffdfad44aacd8b50a6eabec9ba823cb` successfully
3. The next notebook updated `lightning_examples/cifar-baseline` checks out `c0d526ed5b4b4f27f8f4b3f5b0c4bac5b39d0d4c` but when attempting to switch to the publication branch (`5497c9a8dffdfad44aacd8b50a6eabec9ba823cb`) triggers the git-lfs command not to be found in the [post-checkout hook](https://dev.azure.com/Lightning-AI/Tutorials/_build/results?buildId=178971&view=logs&j=be4ec1b1-f10e-5938-8350-483f8bab6f0f&t=98659bc0-d895-5d37-227b-79ed1bd38429&l=18)
4. Publishing of all subsequent notebook updates has since be blocked (the publish pipeline failing with both new commits and re-running of previous runs). Including:
	- [`lightning_examples/cifar-baseline`](https://dev.azure.com/Lightning-AI/Tutorials/_build/results?buildId=178971&view=logs&j=be4ec1b1-f10e-5938-8350-483f8bab6f0f&t=98659bc0-d895-5d37-227b-79ed1bd38429&l=18)
	- [`lightning_examples/datamodules`](https://dev.azure.com/Lightning-AI/Tutorials/_build/results?buildId=178971&view=logs&j=7c6fac96-ab77-5635-5af1-b4c68279a1a9&t=1d9c939f-7d30-5792-7b98-ef0d6029e7ab&l=18)
	- [`lightning_examples/finetuning-scheduler`](https://dev.azure.com/Lightning-AI/Tutorials/_build/results?buildId=179175&view=logs&j=39b3c594-f55d-5bf7-f035-2947d37d58a7&t=f4140e96-52ef-51ca-7c46-f04d3cd10956&l=19)
	- [`course_UvA-DL/07-deep-energy-based-generative-models`](https://dev.azure.com/Lightning-AI/Tutorials/_build/results?buildId=179176&view=logs&j=39b3c594-f55d-5bf7-f035-2947d37d58a7&t=f4140e96-52ef-51ca-7c46-f04d3cd10956&s=96ac2280-8cb4-5df5-99de-dd2da759617d&l=19)
	- re-run of `course_UvA-DL/07-deep-energy-based-generative-models`, fails on [initial checkout attempt (not on the "Git check and Switch" step)](https://dev.azure.com/Lightning-AI/Tutorials/_build/results?buildId=179176&view=logs&j=845ebdc6-563b-55f6-a9ee-d43b2f510a67&t=1d41f30e-325e-55df-1805-a5904a5c4e98&l=441)

Using the latest tutorials docker image I've been able to replicate the entire flow including transitions from the precise refs and branches referenced above but have been unable to reproduce the failure to resolve `git-lfs`. Since I don't have permission to [set pipeline variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops), enable system diagnositics and trigger re-runs I'm not sure I'll be able to efficiently debug much further.

IMHO I think the next step in debugging would be to enable system diagnostics and trigger some new runs as well as adding some additional debugging code prior to the problematic checkout steps. For instance, update "Git check & switch branch" with:
```yaml
      - bash: |
          set +e
          git fetch --all
          echo $(PUB_BRANCH)
          git ls-remote --heads origin ${PUB_BRANCH} | grep ${PUB_BRANCH} >/dev/null
          if [ "$?" == "1" ] ; then echo "Branch doesn't exist"; exit; fi
          apt-get update -q --fix-missing && apt-get install vim strace -y
          strace -o /git_lfs_post_checkout_hook.log -f git checkout ${PUB_BRANCH} 2>&1 && egrep -r "git-lfs\"|execve" /git_lfs_post_checkout_hook.log
          cat /git_lfs_post_checkout_hook.log
          git show-ref $(PUB_BRANCH)
          git pull
          set -e
        displayName: "Git check & switch branch"
```
If necessary of course, one could inject an extended pause prior to executing this step to allow attaching to and debugging within the container to finally nail this problem once and for-all!

I know the Lightning team has a lot of work on its plate so I'm just adding this issue and my observations so it doesn't get lost in the mix and to help minimize your valuable time debugging. 

It'll be great to have notebook updates published automatically once this pipeline issue is resolved. Thanks for all your work!

**Comment by Borda** [comment]
This could be hard to debug from regular PR until we would fuse test and publish stage proposed in #286

**Comment by speediedan** [comment]
#286 is a great idea, fully behind it! Nuke and rebuild might be a good idea as well. 

In the meantime though, I think it might be worth including the debugging lines I added to "git check and switch branch" step (with or without cat of the log) just so we have more visibility into why precisely the post-checkout hook is failing. The next merged PR could then potentially illuminate the problem before #286 gets implemented or the nuke approach. What do you think?
```yaml
      - bash: |
          set +e
          git fetch --all
          echo $(PUB_BRANCH)
          git ls-remote --heads origin ${PUB_BRANCH} | grep ${PUB_BRANCH} >/dev/null
          if [ "$?" == "1" ] ; then echo "Branch doesn't exist"; exit; fi
          apt-get update -q --fix-missing && apt-get install vim strace -y
          strace -o /git_lfs_post_checkout_hook.log -f git checkout ${PUB_BRANCH} 2>&1 && egrep -r "git-lfs\"|execve" /git_lfs_post_checkout_hook.log
          cat /git_lfs_post_checkout_hook.log
          git show-ref $(PUB_BRANCH)
          git pull
          set -e
        displayName: "Git check & switch branch"
```

**Comment by Borda** [comment]
atm, all notebooks can be compiled so I assume all is fine nom but feel free to reopen if you spot it again :flamingo:
